name: oxide_player
description: "A new Flutter project."
publish_to: 'none'
version: 20260131.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.0
  cached_network_image: ^3.4.1

  # Audio Core
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.12
  on_audio_query: ^2.6.0

  # Data
  drift: ^2.30.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  shared_preferences: ^2.5.1

  # System
  permission_handler: ^12.0.1
  audio_session: ^0.2.2
  device_info_plus: ^12.3.0

  # Utils
  get_it: ^9.2.0
  injectable: ^2.3.2
  logger: ^2.6.2
  rxdart: ^0.28.0
  http: ^1.2.1

  provider: ^6.1.2
  file_picker: ^10.3.8
  collection: ^1.19.0
  path: ^1.9.0
  flutter_cache_manager: ^3.3.1
  share_plus: ^12.0.1

  # YouTube Integration
  dio: ^5.4.0
  youtube_explode_dart: ^3.0.5
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^10.0.0
  google_sign_in: 6.2.1
  crypto: ^3.0.7
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.8
  package_info_plus: ^9.0.0
  archive: ^4.0.4
  url_launcher: ^6.3.2
  open_filex: ^4.6.0
  home_widget: ^0.9.0
  metadata_god: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: any
  drift_dev: ^2.30.1
  build_runner: ^2.10.5
  injectable_generator: ^2.9.1
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4
  bloc_test: any
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/lang/
